CREATE TABLE  `devicetracker`.`simcards` (
 `simcard_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ICCID` varchar(30) NOT NULL DEFAULT '',
  `Carrier` varchar(25) NOT NULL DEFAULT '',
  `ID` varchar(25) DEFAULT '',
  `Assigned_To` varchar(50) DEFAULT '',
  `IMSI` varchar(30) DEFAULT '',
  `MSISDN` varchar(30) DEFAULT '',
  `Owner_Name` varchar(50) DEFAULT '',
  `Owner_Contact` varchar(50) DEFAULT '',
  `In_SVV` enum('Y','N') DEFAULT 'Y',
  `Conference_Call` varchar(50) DEFAULT '',
  `International_Call` varchar(50) DEFAULT '',
  `Call_Forwarding` varchar(50) DEFAULT '',
  `Call_Barring` varchar(50) DEFAULT '',
  `Call_Waiting` varchar(50) DEFAULT '',
  `Voice_Mail` varchar(50) DEFAULT '',
  `Notes` varchar(255) DEFAULT '',
  `Util` varchar(7) DEFAULT 'Test',
  `Cost_Jan` decimal(7,2) DEFAULT '0.00',
  `Cost_Feb` decimal(7,2) DEFAULT '0.00',
  `Cost_Mar` decimal(7,2) DEFAULT '0.00',
  `Cost_Apr` decimal(7,2) DEFAULT '0.00',
  `Cost_May` decimal(7,2) DEFAULT '0.00',
  `Cost_Jun` decimal(7,2) DEFAULT '0.00',
  `Cost_Jul` decimal(7,2) DEFAULT '0.00',
  `Cost_Aug` decimal(7,2) DEFAULT '0.00',
  `Cost_Sept` decimal(7,2) DEFAULT '0.00',
  `Cost_Oct` decimal(7,2) DEFAULT '0.00',
  `Cost_Nov` decimal(7,2) DEFAULT '0.00',
  `Cost_Dec` decimal(7,2) DEFAULT '0.00',
  `Sign_out` date DEFAULT '0000-00-00',
  PRIMARY KEY (`simcard_id`) USING BTREE
) ENGINE=MyISAM DEFAULT CHARSET=latin1;